### PR TITLE
build(release): build script now updates most recent archive (#2)

### PR DESCRIPTION
**Pull request by alemagio**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

#2 

## How Has This Been Tested?

I tried several times manually but I will also keep testing it.

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I added a picture of a cute animal cause it's fun

image

NOTE:
As you can see I installed adm-zip, it has no dependency and allowed me to unzip the file easily (even if, apparently there is no way to rename the zipEntry, they also have an open issue, maybe I'll take that one when I can :smile: )
I tried using zlib but had no success, if you have any suggestion feel free to tell me 

I pushed it to be sure we are on the same page and to have feedback

### CODE REVIEW

**Comment by lirantal** [comment]
Looks good.
Now to make this actually work as part of the process of creating and publishing the library we need to call the build script (i.e: `npm run build`) in the github actions workflow, right before we publish. Can you add it?

**Comment by alemagio** [comment]
I simply added to the workflow.
I have one question:
what do we want to do if, for whatever reason, something does wrong while downloading the zip?
I think we should keep the old one right?

**Comment by lirantal** [comment]
If something is wrong with the zip (non existent etc) then it means that release will fail because this step will fail https://twitter.com/maxbeatty/status/1182370039032205313, right?

**Review by lirantal — APPROVED** [review]

**Comment by lirantal** [comment]
@alemagio looks good to me, let's merge it in and see!

**Comment by alemagio** [comment]
> If something is wrong with the zip (non existent etc) then it means that release will fail because this step will fail https://twitter.com/maxbeatty/status/1182370039032205313, right?

I think so.


> @alemagio looks good to me, let's merge it in and see!

I like your approach :joy:

**Comment by lirantal** [comment]
Looks like it works well @alemagio 

Comparing  https://unpkg.com/browse/cwe-sdk@1.0.6/raw/ with https://unpkg.com/browse/cwe-sdk@1.0.5/raw/ looks like we're getting more CWEs :-)

**Pull request merged**
